spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mmall?useUnicode=true&characterEncoding=utf8
    username: root
    password: yuele729
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 1
      max-wait-millis: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      max-total: 20
  #A bean with that name has already been defined and overwriten is disabled
  main:
    allow-bean-definition-overriding: true
    #redis
  redis:
    host: localhost
    port: 6379
    timeout: 10000
    jedis:
      pool:
        min-idle: 2
        max-idle: 8
        max-active: 10
        
 ## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mappers/*.xml
  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.imooc.user.pojo  # 注意：对应实体类的路径
